# cloudbuild.yaml
# Google Cloud Build configuration for SpreadPilot

steps:
  # --- Dependency Installation & Setup ---
  - name: 'python:3.9-slim'
    id: 'Install Core Library'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install --upgrade pip
        cd spreadpilot-core
        pip install .
        cd ..

  # --- Run Unit Tests (Example for one service, repeat/adapt for others) ---
  # Note: Assumes tests are runnable via pytest and dependencies are managed
  - name: 'python:3.9-slim'
    id: 'Test Admin API'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r admin-api/requirements.in -r requirements-dev.in
        pip install ./spreadpilot-core # Install local core lib
        pytest admin-api/tests # Adjust path if needed

  # --- Run Integration Tests ---
  # Note: Requires setting up test environment (e.g., emulators, test DB)
  - name: 'python:3.9-slim'
    id: 'Run Integration Tests'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Setting up integration test environment..."
        # Add commands to set up Firestore emulator, etc. if needed
        pip install --upgrade pip
        pip install -r requirements-dev.in
        pip install ./spreadpilot-core
        # Install all service requirements for integration tests
        pip install -r admin-api/requirements.in
        pip install -r trading-bot/requirements.in # Assuming requirements exist
        pip install -r report-worker/requirements.in
        pip install -r alert-router/requirements.in
        pip install -r watchdog/requirements.in
        echo "Running integration tests..."
        pytest tests/integration

  # --- Build Docker Images (Repeat for each service) ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Admin API Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA', '-f', 'admin-api/Dockerfile', '.'] # Context is root

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Trading Bot Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/trading-bot:$COMMIT_SHA', '-f', 'trading-bot/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Report Worker Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/report-worker:$COMMIT_SHA', '-f', 'report-worker/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Alert Router Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/alert-router:$COMMIT_SHA', '-f', 'alert-router/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Watchdog Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/watchdog:$COMMIT_SHA', '-f', 'watchdog/Dockerfile', '.']

  # --- Build Frontend Image ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '-f', 'frontend/Dockerfile', './frontend'] # Context is frontend dir

  # --- Push Docker Images (Repeat for each service) ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Admin API Image'
    args: ['push', 'gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Trading Bot Image'
    args: ['push', 'gcr.io/$PROJECT_ID/trading-bot:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Report Worker Image'
    args: ['push', 'gcr.io/$PROJECT_ID/report-worker:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Alert Router Image'
    args: ['push', 'gcr.io/$PROJECT_ID/alert-router:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Watchdog Image'
    args: ['push', 'gcr.io/$PROJECT_ID/watchdog:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend Image'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

  # --- Deploy to Dev Environment (Cloud Run Example) ---
  # This step runs only on merges to the 'main' branch (configure trigger)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Admin API to Dev'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'admin-api-dev' # Cloud Run service name for dev
      - '--image=gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA'
      - '--region=us-central1' # Replace with your region
      - '--platform=managed'
      - '--allow-unauthenticated' # Adjust as needed
      - '--set-env-vars=^--^ENV=dev--GCP_PROJECT=$PROJECT_ID' # Example env vars
      # Add --env-vars-from-secret for secrets
      - '--project=$PROJECT_ID'
    waitFor: ['Push Admin API Image'] # Ensure image is pushed first

  # (Repeat deploy step for other services: trading-bot, report-worker, etc.)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Trading Bot to Dev'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'trading-bot-dev', '--image=gcr.io/$PROJECT_ID/trading-bot:$COMMIT_SHA', '--region=us-central1', '--platform=managed', '--project=$PROJECT_ID'] # Add other flags
    waitFor: ['Push Trading Bot Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Report Worker to Dev'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'report-worker-dev', '--image=gcr.io/$PROJECT_ID/report-worker:$COMMIT_SHA', '--region=us-central1', '--platform=managed', '--project=$PROJECT_ID'] # Add other flags
    waitFor: ['Push Report Worker Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Alert Router to Dev'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'alert-router-dev', '--image=gcr.io/$PROJECT_ID/alert-router:$COMMIT_SHA', '--region=us-central1', '--platform=managed', '--project=$PROJECT_ID'] # Add other flags
    waitFor: ['Push Alert Router Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Watchdog to Dev'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'watchdog-dev', '--image=gcr.io/$PROJECT_ID/watchdog:$COMMIT_SHA', '--region=us-central1', '--platform=managed', '--project=$PROJECT_ID'] # Add other flags
    waitFor: ['Push Watchdog Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend to Dev'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'frontend-dev', '--image=gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '--region=us-central1', '--platform=managed', '--allow-unauthenticated', '--project=$PROJECT_ID'] # Add other flags
    waitFor: ['Push Frontend Image']

# --- Tagging for Production Promotion ---
# Tag the successfully built commit SHA with 'dev-latest' for promotion reference
# This assumes the dev deployment steps succeed. A more robust approach might
# involve a final step that only runs if all dev deploys are successful.
# Or, promotion could directly use the COMMIT_SHA if the build passed.

# --- Manual Promotion Trigger ---
# Production deployment should be triggered manually, potentially using a separate
# Cloud Build trigger that references a specific COMMIT_SHA or tag.
# The steps would be similar to the 'Deploy to Dev' steps but target prod services
# and use prod configurations/secrets.

images:
  - 'gcr.io/$PROJECT_ID/admin-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/trading-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/report-worker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/alert-router:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/watchdog:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'

# Timeout for the build
timeout: 3600s # 1 hour

# Options for machine type, logging, etc.
options:
  machineType: 'N1_HIGHCPU_8' # Adjust as needed
  logging: CLOUD_LOGGING_ONLY